# -*- coding: utf-8 -*-
"""flask.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zvnZYmca3PkEZSOHbRh-JLpyNHUDDod9
"""

import pickle
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from flask import Flask,render_template,request
import numpy as np

app=Flask(__name__)
with open('MultinomialNB.pkl','wb')as pickle_file:
  pickle.dump(MultinomialNB,pickle_file)

with open('MultinomialNB.pkl','rb')as pickle_file:
  model=pickle.load(pickle_file)

with open('CountVectorizer.pkl','wb')as pickle_file:
  pickle.dump(CountVectorizer,pickle_file)

with open('CountVectorizer.pkl','rb')as pickle_file:
  transform=pickle.load(pickle_file)

def predict():
	
	if request.method == 'POST':	
		message = str(request.form['message'])
		if message == '':
			prediction = 'empty'
		else:
			to_predict = transformer.transform([message]).toarray()
			prediction = model.predict(to_predict)

	return render_template('result.html',prediction_value = prediction)

if __name__ == '__main__':
	app.run(debug=True)